name_or_path: meta-llama/Llama-3.2-1B-Instruct
tokenizer_name_or_path: meta-llama/Llama-3.2-1B
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float16
fsdp_policy_mp: null
reference_dtype: float16
policy_quantization: 8bit
