name_or_path: Qwen/Qwen2.5-7B-Instruct
tokenizer_name_or_path: Qwen/Qwen2.5-7B-Instruct
archive: null
block_name: Qwen2DecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16
policy_quantization: null